library(shiny)
shinyUI(navbarPage("Black & Scholes",
                   tabPanel("Explanation",
                            mainPanel(
                                    h3('Black & Scholes option calculation'),
                                    p("The Black–Scholes formula calculates the price of European put and call options. 'European' in this case has nothing to do with the continent, but rather the style: an option without the possibility of early exercise. Its calculation depends on 5 variables:"),
                                    p('- the spot (or current) price of the underlying asset'),
                                    p('- the strike (or exercise) price of the option'),
                                    p('- the risk free interest rate'),
                                    p("- the option's maturity date"),
                                    p('- the volatility of the underlying instrument'),
                                    br(),
                                    p('On the Calculation tab these five variables can be set individually through slider adjustments. The call and put option prices for the set strike price will be calculated and adjusted dynamically'))),
                   
                   tabPanel("Calculation",
                            sidebarLayout(
                                    sidebarPanel(
                                        h3('Inputs'),
                                        h4('Spot Price'),
                                        sliderInput("S1",
                                                    h6("Integer"),
                                                    min = 0,
                                                    max = 100,
                                                    value = 51),
                                        sliderInput("S2",
                                                    h6("Decimal"),
                                                    min = 0,
                                                    max = 1,
                                                    step = 0.01,
                                                    value = 0),
                                        br(),
                                        h4('Strike Price'),
                                        sliderInput("X1",
                                                    h6("Integer"),
                                                    min = 0,
                                                    max = 100,
                                                    value = 50),
                                        sliderInput("X2",
                                                    h6("Decimal"),
                                                    min = 0,
                                                    max = 1,
                                                    step = 0.1,
                                                    value = 0),
                                        br(),
                                        sliderInput("vol",
                                                    h4("Volatility (in %)"),
                                                    min = 1,
                                                    max = 100,
                                                    value = 16),
                                        br(),
                                        sliderInput("rate",
                                                    h4("Risk Free Rate (in %)"),
                                                    min = 0,
                                                    max = 15,
                                                    value = 5, 
                                                    step = 0.1),
                                        br(),
                                        dateInput("date", h4("Maturity Date"))
                                ),
                                mainPanel(
                                        h4('the values used for option calculation are:'),
                                        tableOutput("values"),
                                        br(),
                                        h4('option prices:'),
                                        verbatimTextOutput("prices"),
                                        tableOutput("values2"),
                                        br(),
                                        p("test")
                                )
))))